### ISSUE TITLE
Some java software not suitable

### ISSUE THREAD

**Issue by starsareintherose** [TheGreatMcPain/gruvbox-material-gtk#12]
OS: ArchLinux
DE: Gnome
```
java --version                                                                                                          ░▒▓ ✔  21:38:34  ▓▒░
openjdk 17 2021-09-14
OpenJDK Runtime Environment (build 17+35)
OpenJDK 64-Bit Server VM (build 17+35, mixed mode)

```
![image](https://user-images.githubusercontent.com/37733075/139557750-7e5092af-9cec-4326-b827-ccea32ca23a7.png)

**Comment by TheGreatMcPain** [comment]
Can you try a different theme that's based on `Materia`?

I really have know idea how to debug/fix stuff like this, because the theme is just generated using [oomox](https://github.com/themix-project/oomox).

**Comment by TheGreatMcPain** [comment]
I'm cleaning up some inactive issues please re-open if needed.
