### ISSUE TITLE
Add the dark soft variant

### ISSUE THREAD

**Issue by gustavothecoder** [TheGreatMcPain/gruvbox-material-gtk#14]
Hi!

I made the port for the dark soft variant and I would like to include in the project, it looks like this:

![dark_soft](https://user-images.githubusercontent.com/57065994/156189473-14feadca-0b4c-4830-9062-374dd9e45f79.png)

What do you think?

**Comment by TheGreatMcPain** [comment]
Looks pretty good.

If you have the oomox config I can add it to the repository.

**Comment by gustavothecoder** [comment]
I don't have the oomox config, I just made a copy of the original theme and replaced the background colors.
