### ISSUE TITLE
I wanted to Hack the Theme 

### ISSUE THREAD

**Issue by Deottive** [TheGreatMcPain/gruvbox-material-gtk#16]
I am really new to Gtk schemes and trying to learn and wanted to learm how can I increase or decrease the Border radius of windows like the amount of the corners which are curved so I wanted to change them from something like 4 to 8 or something. Please help. Like what should I change and where are the files for that

**Comment by TheGreatMcPain** [comment]
This theme was created using [oomox](https://github.com/themix-project/oomox).

The configuration files for this theme is located on the [config branch](https://github.com/TheGreatMcPain/gruvbox-material-gtk/tree/config) of this repository.  You'd just have to put them in `~/.config/oomox`.
