### ISSUE TITLE
Not an issue; just wanted to say thanks

### ISSUE THREAD

**Issue by etherrorcode404** [TheGreatMcPain/gruvbox-material-gtk#18]
https://github.com/etherrorcode404/gruvbox-material-gtk 
i made a fork of this!
Thanks a lot for your theme its sweet! You could check out my fork..

**Comment by TheGreatMcPain** [comment]
Thank you, but you should also thank [sainnhe](https://github.com/sainnhe) who was the original owner of this repo.
