### ISSUE TITLE
Update the theme with new icons

### ISSUE THREAD

**Issue by vanillajonathan** [TheGreatMcPain/gruvbox-material-gtk#20]
The icon theme is outdated and lacks some new icons such as `sidebar-show-symbolic`.

**Comment by TheGreatMcPain** [comment]
I've regenerated both the icon theme and the GTK theme using the latest version of themix-gui.  Can you see if `sidebar-show-symbolic` exists?

Otherwise you might have to take this issue to the upstream icon theme [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme), or the GTK theme [Materia](https://github.com/nana-4/materia-theme).

**Comment by vanillajonathan** [comment]
Thanks, this fixed it for me!

**Comment by vanillajonathan** [comment]
Can you regenerate the icons again for GTK 4.8.3?

It contains a new grid icon to toggle the grid in the file picker dialog.

**Comment by TheGreatMcPain** [comment]
I just regenerated the icons.  Is it fixed?

**Comment by vanillajonathan** [comment]
I am not sure, the `view-grid-symbolic` icon in a Flatpak application is not rendered, but maybe that has something to do with Flatpak because I see the icons contains the `/symbolic/actions/view-grid-symbolic.svg` file.

However, my folder icons used to be green (just like in the screenshot in this repository) but now they're red. Also my Firefox Nightly icon seems to have disappeared.

**Comment by TheGreatMcPain** [comment]
I suggest filing an issue with PapirusDevelopmentTeam/papirus-icon-theme then.

**Comment by vanillajonathan** [comment]
From the README file in the papirus-icon-theme repository it seems it supports colors for the folders. Maybe this is a configuration thing that you can set when you generate them?

**Comment by TheGreatMcPain** [comment]
> However, my folder icons used to be green (just like in the screenshot in this repository) but now they're red. Also my Firefox Nightly icon seems to have disappeared.

You might want to double check your installation, because my folder icons are still green.

> From the README file in the papirus-icon-theme repository it seems it supports colors for the folders. Maybe this is a configuration thing that you can set when you generate them?

Yes, themix-gui (the tool used to make this theme) allows you to change the folder icon colors.

**Comment by vanillajonathan** [comment]
Okay I just re-downloaded the icons, extracted them, removed the old icons, and copied over the icons again and now the folder icons are green again and the Firefox icon is back. Not sure what went wrong the last time time, but now it works, thanks!
