### ISSUE TITLE
Black border around dock

### ISSUE THREAD

**Issue by wooshdude** [TheGreatMcPain/gruvbox-material-gtk#21]
Im using Gnome on Pop!_os and there is a black border around my dock (edges not extended). Im new to the custom themes community, and linux generally, so any help would be appreciated! Thanks <3
![image](https://user-images.githubusercontent.com/63532428/211134113-0162cd2e-492c-466e-bec6-483e764ce29a.png)

**Comment by wooshdude** [comment]
This issue persists on Gruvbox-Material-Dark and Gruvbox-Material-Dark-HIDPI btw.

**Comment by TheGreatMcPain** [comment]
Sorry, for the late response.

Does this happen with [materia-theme](https://github.com/nana-4/materia-theme)?

If it does there's not much I can do, since this theme is pretty much a recolor of materia.

**Comment by TheGreatMcPain** [comment]
I'm gonna go ahead and close this.

Please re-open if this issue still persists.
