### ISSUE TITLE
Theme colors are broken (default material blue and white background) 

### ISSUE THREAD

**Issue by MathisP75** [TheGreatMcPain/gruvbox-material-gtk#22]
![1682286334_grim](https://user-images.githubusercontent.com/98901170/233867948-e8d1bd5f-d0e3-44ba-b8ca-8d65df3f27b9.png)
On Arch Linux, both with the AUR version and a manually installed version.

**Comment by TheGreatMcPain** [comment]
What's the name of those file managers?

On my system I've tried `pcmanfm` (both gtk and qt versions) and the theme colors are working just fine.

**Comment by MathisP75** [comment]
That's thunar (left) and nautilus (right).

**Comment by TheGreatMcPain** [comment]
Thunar looks fine on my system, while Nautilus seems to be using it's own default theme, which I'm not sure how to change without installing gnome-tweaks.

**Comment by MathisP75** [comment]
Does Thunar have the correct accent color? Because the soft blue from the material theme is everywhere in the gtk configs.

**Comment by TheGreatMcPain** [comment]
Here's a screenshot of Thunar from my system.

![thunar-gruvbox](https://user-images.githubusercontent.com/6900584/233895442-55dcaf5d-21f3-48f4-9c67-9a12bdee8938.png)

**Comment by MathisP75** [comment]
What if you open tabs and set the file path to buttons? I could try fixing it and make a pr.

**Comment by TheGreatMcPain** [comment]
> What if you open tabs and set the file path to buttons?
I don't use GUI filemanagers, so I have no idea what you mean by setting a file path to buttons.

Plus, I really don't see what's wrong with my screenshot.  The demo picture is probably outdated, but the theme has looked like my screenshot for years now.  I don't remember adding the blue.  If I did it was probably to fix text readability on some applications.

**Comment by TheGreatMcPain** [comment]
I've done a little digging and found that the "Selection Background" color did change some at some point.  I'm pretty sure it was due to a program I was using a while back not rendering the text color properly causing it the text to be invisible, so I switched it to a blue from [sainnhe/gruvbox-material](https://github.com/sainnhe/gruvbox-material) and didn't bother to update the demo screenshot.

I've went back and changed the "Selection Background" color to what it was. See: e3966b7

**Comment by MathisP75** [comment]
Awesome

**Comment by TheGreatMcPain** [comment]
You think we can close this?

`pcmanfm` and `thunar` displays the theme properly.

As for `nautilus` I think that's due to Materia and `themix-gui` not working with `libadwaita` yet.

**Comment by MathisP75** [comment]
I guess so!
