### ISSUE TITLE
GTK4 theme's widgets are strange

### ISSUE THREAD

**Issue by breeze256** [TheGreatMcPain/gruvbox-material-gtk#24]
I put the theme in `/usr/share/themes` and icon in `/usr/share/icons`  
And for me, the gtk3 theme looks good, but gtk4 theme has some issues, looks like follow pictures:
![Snapshot_2024-07-20_16-54-01](https://github.com/user-attachments/assets/6f716acc-a548-49ad-a47a-f35cf7f6fc67)
![Snapshot_2024-07-20_16-53-38](https://github.com/user-attachments/assets/e34ee122-d91b-4acf-8a69-b15a11204718)
And how can I deal with it? Thx

**Comment by TheGreatMcPain** [comment]
I'm still not sure how to fix that.  I'll check to see if updating with themix-gui will do anything, but I have my doubts.

**Comment by TheGreatMcPain** [comment]
Well, I've re-generated the icons, but the materia theme hasn't seen any updates since January 2023.  I have a feeling re-generating the theme itself won't fix your issue considering themix-gui still doesn't support GTK4 yet.
